ashuprince121/Prepration_Code_Repository_HACKTOBERFEST-2021

- CONTRIBUTING.md
- README.md
This PR adds the CONTRIBUTION file, with all basic explanation of How to contribute to this project, the information is basic and useful for anyone. Any tips I am waiting for your review
> Resolves #1 - add contribution section

- Python code/whatsappSpammer.py
A simple script to spam your friend whatsapp chat
> added python whatsapp spammer

- C code/Factors.c
- C code/Palindrome.c
- C code/PowerOfNumber.c
- Prime Number
> Prime Number.c

- Python code/multiply two matrices.py
- Python code/program to count  vowels.py
- Python code/sorting alphabetically.py
- Python code/transpose matrix.py
Program to multiply two matrices using nested loops
Program to count the number of each vowels
Program to sort alphabetically the words form a string provided by the user
Program to transpose a matrix using a nested loop
> added 4 programs

- JAVA codes/Java code to calculate simple interest
Added Java code to calculate simple interest
> Create Java code to calculate simple interest

- C code/LinearSearchRecursive.c
- C code/QuadraticEquationSolver.c
- C code/SubStringRemover.c
- C code/factorial.c
- C code/factorialRecursive.c
- C code/perfectSquare.c
- C code/primeNumbersRange.c
- C code/stringPalindrome.c
<h3>Programs added</h3>
<ol>
<li>Find factorial using recursive function</li>
<li>Find factorial using normal for loop</li>
<li>Check whether a number is a perfect square</li>
<li>Print prime numbers in a given range</li>
<li>Check whether a given string is a palindrome</li>
</ol>
> Added 5 useful C programs

- C code/ArmstrongNumberRange.c
- C code/QuadraticEquationSolver.c
- JAVA codes/ArmstrongNumberRange.java
- JAVA codes/EquationSolver.java
<ol>
<h3>Programs added</h3>
<li>EquationSolver.java</li>
<li>ArmstrongNumberRange.java</li>
<li>ArmstrongNumberRange.c</li>
</ol>
<p>Simplified code in QuadraticEquationSolver.c</p>
> Added new programs and made a small change

- C++ code/Array of Objects
C++ program example of array of objects
> Array of Objects

- Newton Raphson Method
C program to find the value using Newton Raphson Method
> Newton Raphson Method

- JAVA codes/Reverse string
Java program to reverse string
> String Reversal

- C++ code/Simplex Method
Simplex Method using economic function is used to find maximum and minimum value
> Simplex Method

- C++ code/VAM method
Value Added Method in transportation problem is used to find the least cost
> VAM method

- C code/binary search
Implemented binary search algorithm in C language.
> Create binary search

- C++ code/Euler Graph Formula
Eulerian circuits is that all vertices in the graph have an even degree
> EulerGraph

- C code/CalculateGrossSalary.c
- C code/Centigrade_to_farenheit.c
- C code/CheckTriangle.c
- C code/CovertRoman.c
- C code/DayOfTheYear.c
- C code/draw_box.c
- C code/euclidean_alg.c
added basic C programs, namely:
CalculateGrossSalary.c
1. Centigrade_to_farenheit.c
2. CheckTriangle.c
3. CovertRoman.c
4. DayOfTheYear.c
5. draw_box.c
6. euclidean_alg.c
> added basic C programs

- Python code/Transportation Problem
Python program to find the cost of minimum and maximum cost of transportation
> Transportation Problem

- Distinct Number Of Islands in 2D Matrix
Given a boolean 2D matrix, the task is to find the number of distinct islands where a group of connected 1s (horizontally or vertically) forms an island. Two islands are considered to be distinct if and only if one island is equal to another.
> Create Distinct Number Of Islands in 2D Matrix

- Javascript code/operation_arithmetic.js
hello, i adding  folder Javascript code in which there is a file operation_arithmetic.js
> adding operation_arithmetic.js

- Python code/mad__libs.py
> Added Mad Libs Program

- Javascript code/manually-sorting.js
Reference from contribution section
I create example manually sorting algorithm with javascript, i hope my example help everyone who learn javascript, algorithm or others.
Thank you
> add manually sorting algorithm with javascript

- Python code/Audiobook Voice-Over.py
python cersion 8 required to run
> Added a Audiobook Voice-Over
